import os
from pathlib import Path
from dotenv import load_dotenv

# ============================================================
# LOAD ENVIRONMENT VARIABLES
# ============================================================

# Load .env when running locally
load_dotenv()


# ============================================================
# BASE DIRECTORY
# ============================================================

# Project root directory
BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# GROQ API KEY
# ============================================================

# First try environment variable (.env locally)
GROQ_API_KEY = os.getenv("GROQ_API_KEY")

# If not found, try Streamlit Secrets (Streamlit Cloud)
if not GROQ_API_KEY:
    try:
        import streamlit as st

        if "GROQ_API_KEY" in st.secrets:
            GROQ_API_KEY = st.secrets["GROQ_API_KEY"]

    except Exception:
        GROQ_API_KEY = None


# Stop the application if the API key is not configured
if not GROQ_API_KEY:
    raise ValueError(
        "GROQ_API_KEY is not configured. "
        "For local development, add it to your .env file. "
        "For Streamlit Cloud, add it under App Settings → Secrets."
    )


# ============================================================
# MODEL CONFIGURATION
# ============================================================

# Groq model
MODEL_NAME = "llama-3.3-70b-versatile"


# ============================================================
# DATA DIRECTORY
# ============================================================

# Directory containing your aviation documents
DATA_DIR = BASE_DIR / "data"


# ============================================================
# CHROMA VECTOR DATABASE
# ============================================================

# Location of the Chroma vector database
CHROMA_DB_DIR = BASE_DIR / "chromadb"


# ============================================================
# EMBEDDING MODEL
# ============================================================

# HuggingFace embedding model
EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"


# ============================================================
# TEXT CHUNKING CONFIGURATION
# ============================================================

# Number of characters in each document chunk
CHUNK_SIZE = 1000

# Number of overlapping characters between chunks
CHUNK_OVERLAP = 200


# ============================================================
# RETRIEVAL CONFIGURATION
# ============================================================

# Number of documents/chunks retrieved for each question
TOP_K = 5


# ============================================================
# LLM GENERATION PARAMETERS
# ============================================================

# Temperature controls how creative/random the response is
TEMPERATURE = 0.1

# Maximum number of tokens generated by the model
MAX_TOKENS = 2048
